### ISSUE TITLE
feat(CreateProject): wrap stepper in form

### ISSUE THREAD

**Issue by HawaKallon** [christex-foundation/pipeline#110]
- remove forms from all the components
- wrap the entire stepper in a form
- redesign page

**Comment by sparrowsl** [comment]
quick question to clarify
> wrap the entire stepper in a form

does this mean we make the stepping process into a giant long form _(like one page)_??

**Comment by HawaKallon** [comment]
@sparrowsl yup that's what we were thinking of doing to handle the form better
