### ISSUE TITLE
add project UI design

### ISSUE THREAD

**Issue by sparrowsl** [christex-foundation/pipeline#120]
Currently there is no UI design available that an external contributor will look at and see how the final platform is supposed to look like.
Would be cool to get a figma link or even an image(s) of how it should look.

**Comment by cogoo** [comment]
Sure, will add this to the readme;

for now you can find the relevant docs here:
https://fndn.notion.site/Pipeline-7ca1b61d0c874813b445b336d8a7353d?pvs=4
