### ISSUE TITLE
feat(nav): redesign

### ISSUE THREAD

**Issue by HawaKallon** [christex-foundation/pipeline#133]
- implementing the new design
- https://www.figma.com/design/YLNpdRoJHHN7nwhOSIRqS2/Pipeline---FINAL?node-id=0-1&node-type=canvas&m=dev

**Comment by cogoo** [comment]
@HawaKallon could you add a link to the figma in the issue please

**Comment by HawaKallon** [comment]
@cogoo added

**Comment by sparrowsl** [comment]
I think this has been closed
