### ISSUE TITLE
Empty addTemaMember function should be implemented or removed.

### ISSUE THREAD

**Issue by Iyeba-Kallon** [christex-foundation/pipeline#151]
The addTemaMember function is defined but does not have any implementation. This may cause confusion for other developers working on the code.

**Steps to Reproduce:**

- Open the code and inspect the addTemaMember function.

**Expected Behavior:** The function should either be implemented to handle team member additions or be removed if unnecessary.

**Suggested Fix:** Implement the logic for adding a team member or remove the function if it is not needed.

**Comment by sparrowsl** [comment]
@Iyeba-Kallon can you please direct in which file the function lives.
I couldn't find it at all.
